module.exports = {
    root: true,
    env: {
        browser: true,
        es2021: true,
        node: true,
    },
    plugins: [
        "react",
        "jsx-a11y",
        "unused-imports",
        "@typescript-eslint",
        "react-hooks",
    ],
    extends: [
        "airbnb",
        "airbnb/hooks",
        "plugin:jsx-a11y/recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "prettier",
    ],
    parserOptions: {
        ecmaFeatures: {
            jsx: true,
        },
        ecmaVersion: "latest",
        sourceType: "module",
        project: "./tsconfig.json",
        tsconfigRootDir: __dirname,
    },
    rules: {
        "jsx-a11y/click-events-have-key-events": "warn",
        "jsx-a11y/label-has-associated-control": "warn",
        "jsx-a11y/no-noninteractive-element-interactions": "warn",
        "jsx-quotes": ["error", "prefer-single"],
        "no-unused-vars": "warn",
        "react/function-component-definition": "off",
        "react/react-in-jsx-scope": "off",
        "react/prop-types": "warn",
        semi: ["warn", "always"],
        "no-console": ["warn", { allow: ["warn", "error", "info"] }],
        "prefer-spread": ["warn"],
        "no-extra-semi": ["warn"],
        quotes: ["warn", "single"],
        "linebreak-style": ["warn", "unix"],
        "@typescript-eslint/indent": ["warn", 2],
        "@typescript-eslint/no-empty-interface": ["off"],
        "@typescript-eslint/camelcase": ["off"],
        "@typescript-eslint/restrict-plus-operands": ["warn"],
        "@typescript-eslint/array-type": ["off"],
        "@typescript-eslint/no-use-before-define": ["off"],
        "@typescript-eslint/no-angle-bracket-type-assertion": ["off"],
        "@typescript-eslint/interface-name-prefix": ["off"],
        "@typescript-eslint/explicit-member-accessibility": ["warn"],
        "@typescript-eslint/consistent-type-assertions": ["warn"],
        "@typescript-eslint/no-inferrable-types": ["warn"],
        // react hook
        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "warn",
    },
};
